import networks.pspnet
import networks.pspnet_pop
import networks.pspplus_pop
import networks.deeplab_pop
import networks.vggunet_pop
import networks.seghr_pop
import networks.convnext_pop
import networks.swin_pop
import networks.lsk_pop